# Generated by Django 2.1.2 on 2018-10-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Başlık buraya yazılacak', max_length=100, unique=True, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True)),
                ('body', models.TextField(default='', help_text='Makale buraya yazılacak', verbose_name='İçerik')),
                ('author', models.CharField(default='', help_text='Yazar', max_length=20, verbose_name='Yazar')),
                ('category', models.CharField(default='', max_length=10, verbose_name='Kategori')),
                ('durum', models.BooleanField(default=True, verbose_name='Erişim')),
                ('date', models.DateTimeField(auto_now=True)),
                ('timeread', models.CharField(choices=[('1', '1dk'), ('2', '2dk'), ('3', '3dk'), ('4', '4dk')], default=2, max_length=2, verbose_name='Okuma Süresi')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kategori İsmi Yazılacak', max_length=100, unique=True, verbose_name='Kategori')),
                ('durum', models.BooleanField(default=True, verbose_name='Erişime Açık')),
            ],
        ),
    ]
