# Generated by Django 2.1.2 on 2018-11-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_auto_20181031_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='dateet',
            field=models.DateTimeField(auto_now=True, verbose_name='Oluşturulma Zamanı'),
        ),
    ]
