# Generated by Django 2.1.2 on 2018-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Başlık buraya yazılacak', max_length=100, unique=True),
        ),
    ]
