# Generated by Django 2.1.2 on 2018-11-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0003_auto_20181101_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
    ]
