# Generated by Django 2.1.2 on 2018-11-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0005_auto_20181101_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(default='', max_length=10, verbose_name='Kategori'),
        ),
    ]
