# Generated by Django 2.1.2 on 2018-11-01 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0006_auto_20181101_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uygulama.Category', verbose_name='Kategori'),
        ),
    ]
