# Generated by Django 2.1.2 on 2018-11-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0007_auto_20181101_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='adet',
            field=models.IntegerField(default=0, verbose_name='İçerik Sayısı'),
        ),
    ]
