# Generated by Django 2.1.2 on 2018-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uygulama', '0010_auto_20181101_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(default='', help_text='Otomatik oluşturulacak', max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', help_text='Otomatik oluşturulacak', max_length=100, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='timeread',
            field=models.CharField(choices=[('1', '1dk'), ('2', '2dk'), ('3', '3dk'), ('4', '4dk'), ('5', '5dk'), ('6', '6dk'), ('7', '7dk')], default=1, max_length=2, verbose_name='Okuma Süresi'),
        ),
    ]
